#!/usr/bin/env lua

package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

local config_dir = os.getenv("CONFIG_DIR") or os.getenv("HOME") .. "/.config/sketchybar"
package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path

sbar = require("sketchybar")

sbar.exec("pkill -f sketchybar_daemon", function()
	sbar.exec("$HOME/dev/daemons/sketchybar-daemon/build/sketchybar_daemon &")
end)

sbar.begin_config()
require("main")
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
